services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    container_name: paichanpay_web
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env